name: bidau

services:
  bidding:
    build:
      context: ./bidding
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
  bidding-1:
    build:
      context: ./bidding
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    restart: always
  bidding-2:
    build:
      context: ./bidding
      dockerfile: ./Dockerfile
    ports:
      - "8082:8080"
    restart: always
  auction:
    build:
      context: ./auction
      dockerfile: ./Dockerfile
    ports:
      - "8084:8443"
    restart: always
